name : Demo-1 
on: 
 push:
  
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v3
   - name: docker build Image 
     run: docker build -t pyimage:v1 .
   - name: Run Container Image
     run: docker run -d --name cont1 -p 5000:5000 pyimage:v1
   - name: Smoke Test
     run: |
       sleep 5
       curl http://localhost:5000/health
         
